"""Sales Order doc_event handlers for landms.

Three things happen on the Sales Order lifecycle:

  validate (draft and resubmit)
    - guard rails for SOs that came from a Plot Application
    - block manual edits to control_number (it's read-only in the UI but
      defensive belt + braces here too)

  on_submit
    - generate a TCB control number (idempotent — never regenerates)
    - create the TCB Control Number registry row
    - call register_reference_for_sales_order() to push to TCB
    - flip the linked Plot Application to Converted (if any)
    - flip the Plot Master to Pending Advance (if it was Available)

  on_cancel
    - call decline_reference_for_sales_order() to invalidate the CN at TCB
    - registry → Declined
    - apply decline_failure_policy: Block Cancel throws, Allow flags

A Sales Order is considered "in scope" for landms only if it has a `plot`
custom field set. SOs that don't touch a plot pass through untouched.
"""

import frappe
from frappe.utils import cstr, flt

from landms.tcb import (
	create_or_get_registry,
	decline_reference_for_sales_order,
	generate_control_number,
	is_valid_control_number,
	register_reference_for_sales_order,
	_get_tcb_settings,
)


# ---------------------------------------------------------------------- #
#  Scope check                                                             #
# ---------------------------------------------------------------------- #


def _is_landms_sales_order(doc) -> bool:
	"""True iff this SO has a plot link — meaning it's a plot sale, not
	a vanilla ERPNext SO that should be left alone.
	"""
	return bool(doc.get("plot"))


# ---------------------------------------------------------------------- #
#  validate                                                                #
# ---------------------------------------------------------------------- #


def validate_sales_order(doc, method=None):
	if not _is_landms_sales_order(doc):
		return

	_block_manual_control_number(doc)
	_validate_plot_application_link(doc)


def _block_manual_control_number(doc):
	"""Defensive guard against API/Bench setting control_number directly.

	The field is read_only in the UI, but a frappe.set_value bypass is still
	possible. We allow:
	  - empty (will be generated on submit)
	  - unchanged (already-stored value)
	  - a value matching our pattern (regenerated by submit hook)

	We block: any new value that doesn't match the pattern.
	"""
	value = cstr(doc.get("control_number") or "").strip()
	if not value:
		return

	if not doc.is_new() and frappe.db.has_column("Sales Order", "control_number"):
		stored = frappe.db.get_value("Sales Order", doc.name, "control_number")
		if value == cstr(stored or "").strip():
			return  # unchanged

	if not is_valid_control_number(value):
		frappe.throw(
			"TCB Control Number cannot be set manually. It is generated by the "
			"system on Sales Order submit. Clear the field and re-save."
		)


def _validate_plot_application_link(doc):
	"""If linked to a Plot Application, the application must be Paid and
	for the same plot/customer."""
	app_name = doc.get("plot_application")
	if not app_name:
		return
	if not frappe.db.exists("Plot Application", app_name):
		frappe.throw(f"Linked Plot Application {app_name} not found.")

	app = frappe.db.get_value(
		"Plot Application", app_name,
		["status", "plot", "customer"], as_dict=True,
	)
	if app.status not in ("Paid", "Converted"):
		frappe.throw(
			f"Plot Application {app_name} is {app.status}. "
			"Only Paid (or already-Converted) applications can back a Sales Order."
		)
	if app.plot != doc.plot:
		frappe.throw(
			f"Sales Order plot ({doc.plot}) does not match application plot ({app.plot})."
		)
	if app.customer != doc.customer:
		frappe.throw(
			f"Sales Order customer ({doc.customer}) does not match "
			f"application customer ({app.customer})."
		)


# ---------------------------------------------------------------------- #
#  on_submit                                                               #
# ---------------------------------------------------------------------- #


def submit_sales_order(doc, method=None):
	if not _is_landms_sales_order(doc):
		return

	control_number = _ensure_control_number(doc)
	_create_registry_row(doc, control_number)
	_register_with_tcb(doc, control_number)
	_advance_plot_application(doc)
	_advance_plot_master(doc)


def _ensure_control_number(doc) -> str:
	"""Idempotent: generate only if not already set, then persist via db_set
	so the in-memory doc and the DB row stay in sync.
	"""
	current = cstr(doc.get("control_number") or "").strip()
	if current and is_valid_control_number(current):
		return current

	new_cn = generate_control_number(doc.name)
	doc.db_set("control_number", new_cn)
	doc.control_number = new_cn
	return new_cn


def _create_registry_row(doc, control_number: str) -> None:
	"""Create the TCB Control Number registry row, idempotent."""
	try:
		create_or_get_registry(
			control_number=control_number,
			sales_order=doc.name,
			customer=doc.customer,
			amount=flt(doc.grand_total),
		)
	except Exception:
		# Registry creation failure must not block the SO submit, but we
		# need to know about it. Log and continue — the registry can be
		# back-filled by a maintenance script if needed.
		frappe.logger("landms").error(
			f"Failed to create TCB Control Number registry row for {doc.name}",
			exc_info=True,
		)


def _register_with_tcb(doc, control_number: str) -> None:
	"""Push the reference to TCB. Block submit if Live mode and call fails."""
	settings = _get_tcb_settings()
	result = register_reference_for_sales_order(doc.name, control_number)

	# In Live mode, a failed registration means TCB doesn't know about the
	# control number — so the customer can never pay against it. Block.
	if settings.get("outbound_mode") == "Live" and not result.get("ok"):
		frappe.throw(
			f"TCB reference registration failed for control number {control_number}: "
			f"{result.get('message') or 'unknown error'}. "
			"Sales Order submit blocked. Check TCB API Log for details."
		)


def _advance_plot_application(doc) -> None:
	"""Flip Plot Application to Converted on first SO submit."""
	app_name = doc.get("plot_application")
	if not app_name:
		return
	current_status = frappe.db.get_value("Plot Application", app_name, "status")
	if current_status == "Paid":
		frappe.db.set_value("Plot Application", app_name, "status", "Converted")


def _advance_plot_master(doc) -> None:
	"""Move plot from Available → Pending Advance on first SO submit."""
	if not doc.plot:
		return
	current = frappe.db.get_value("Plot Master", doc.plot, "status")
	if current == "Available":
		frappe.db.set_value("Plot Master", doc.plot, "status", "Pending Advance")


# ---------------------------------------------------------------------- #
#  on_cancel                                                               #
# ---------------------------------------------------------------------- #


def cancel_sales_order(doc, method=None):
	if not _is_landms_sales_order(doc):
		return

	control_number = cstr(doc.get("control_number") or "").strip()
	if not control_number:
		return  # nothing to decline

	_block_cancel_if_paid(doc)

	settings = _get_tcb_settings()
	result = decline_reference_for_sales_order(doc.name, control_number)

	if not result.get("ok") and result.get("block_cancel"):
		# Block Cancel policy: throw to abort the cancellation.
		frappe.throw(
			f"TCB Decline call failed for control number {control_number} and "
			f"the Decline Failure Policy is set to 'Block Cancel'. "
			f"Cancellation aborted. Detail: {result.get('message')}"
		)


def _block_cancel_if_paid(doc):
	"""Don't let an SO be cancelled after a payment has landed against it.

	Once Plot Contract is created and money has flowed, the path to undo is
	contract termination (which posts forfeiture JE), not SO cancellation.
	"""
	plot_invoice = doc.get("plot_sales_invoice")
	if plot_invoice and frappe.db.exists("Sales Invoice", plot_invoice):
		outstanding, grand_total = frappe.db.get_value(
			"Sales Invoice",
			plot_invoice,
			["outstanding_amount", "grand_total"],
		)
		if flt(outstanding) < flt(grand_total):
			frappe.throw(
				f"Sales Order {doc.name} cannot be cancelled — payment has been "
				f"received against Sales Invoice {plot_invoice}. "
				"Use Plot Contract → Terminate Contract instead."
			)
